-- MySQL Script generated by MySQL Workbench
-- Mon Jan  8 20:49:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies_db` DEFAULT CHARACTER SET utf8 ;
USE `movies_db` ;

-- -----------------------------------------------------
-- Table `movies_db`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movie` (
  `idmovie` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NULL,
  `desc` VARCHAR(1000) NULL,
  `runtime` INT NULL,
  `release` INT NULL,
  `poster_path` VARCHAR(500) NULL,
  `vote_count` INT NULL,
  `avg_vote` DOUBLE NULL,
  PRIMARY KEY (`idmovie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`genre` (
  `idgenre` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(100) NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`movie_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movie_genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre_idgenre` INT NOT NULL,
  `movie_idmovie` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movie_genre_genre_idx` (`genre_idgenre` ASC),
  INDEX `fk_movie_genre_movie1_idx` (`movie_idmovie` ASC),
  CONSTRAINT `fk_movie_genre_genre`
    FOREIGN KEY (`genre_idgenre`)
    REFERENCES `movies_db`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_genre_movie1`
    FOREIGN KEY (`movie_idmovie`)
    REFERENCES `movies_db`.`movie` (`idmovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `role_name` ENUM('Actor', 'Director') NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`person` (
  `idperson` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(250) NULL,
  `last_name` VARCHAR(250) NULL,
  `gender` ENUM('M', 'F') NULL,
  `date_of_birth` DATE NULL,
  PRIMARY KEY (`idperson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`movie_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movie_person` (
  `movie_idmovie` INT NOT NULL,
  `role_idrole` INT NOT NULL,
  `person_idperson` INT NOT NULL,
  INDEX `fk_movie_person_movie1_idx` (`movie_idmovie` ASC),
  INDEX `fk_movie_person_role1_idx` (`role_idrole` ASC),
  INDEX `fk_movie_person_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_movie_person_movie1`
    FOREIGN KEY (`movie_idmovie`)
    REFERENCES `movies_db`.`movie` (`idmovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_person_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `movies_db`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_person_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `movies_db`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_user_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `movies_db`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
